package uk.co.twinscrollgridbalancer.tsgbheater.remote

import kotlinx.serialization.Serializable

// One paired Windows server. Generated by the Windows app's pairing QR;
// stored locally so the phone can sign every request and pin the cert.
@Serializable
data class PairedServer(
    val id:            String,    // local UUID
    val label:         String,    // user-friendly name
    val baseUrl:       String,    // https://1.2.3.4:8800
    val keyId:         String,    // server-issued key id
    val secretBase64:  String,    // base64 (NOT base64url) 32-byte secret
    val certSha256Hex: String,    // SHA-256 hex of the server's leaf cert (cert pin)
    val pairedAtMs:    Long,
)
